services:
  mysql:
    image: mysql:8.4.5
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
  redis:
    image: redis:7.4
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
  meilisearch:
    image: getmeili/meilisearch:v1.13
    environment:
      - MEILI_ENV=development
      - MEILI_MASTER_KEY=SvuHwKxo38ozc0extjpI-Fi-uzYl5MmTYyDMfkwmolk
    ports:
      - "7700:7700"
    volumes:
      - ./data/meili_data:/meili_data
