function hello(r) {
    r.headersOut['Content-Type'] = 'text/html';
    r.return(200, `
<!DOCTYPE html>
<html>
<head>
    <title>Hello World</title>
    <style>
        body {
            text-align: center;
            margin-top: 100px;
        }
        h1 {
            color: #2c3e50;
        }
    </style>
</head>
<body>
    <h1>Hello World from njs!</h1>
    <p>This page was generated by Nginx JavaScript module</p>
</body>
</html>
    `);
}

export default { hello };
